spring:
  main:
    web-application-type: none
    banner-mode: off
  datasource:
    hikari:
      pool-name: educ-grad-trax-api-cp
      maximum-pool-size: 10
      connection-timeout: 60000
      max-lifetime: 60000
    url: ${TRAX_DB_CONNECTION_STRING}
    username: ${TRAX_DB_USERNAME}
    password: ${TRAX_DB_PASSWORD}
    driver-class: oracle.jdbc.driver.OracleDriver
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: none
logging:
  level:
    root: off
gtts-properties:
  grad-api-base-url: https://dev.grad.gov.bc.ca/
  os-hosted-url: ${OS_HOSTED_URL}
  auth:
    student-api-client-id: ${STUDENT_API_CLIENT_ID}
    student-api-client-secret: ${STUDENT_API_CLIENT_SECRET}
    student-api-username: ${STUDENT_API_USERNAME}
    student-api-password: ${STUDENT_API_PASSWORD}
  service-endpoints:
    keycloak-auth-host: ${KEYCLOAK_AUTH_HOST}
    students-api: https://educ-grad-student-api-${gtts-properties.os-hosted-url}
    students-api-projectedgrad-list: https://educ-grad-student-api-${gtts-properties.os-hosted-url}/api/v1/student/projected
    students-api-search-by-pen: https://educ-grad-student-api-${gtts-properties.os-hosted-url}/api/v1/student/pen/{pen}
    grad-algorithm-api-graduate: https://educ-grad-algorithm-api-77c02f-dev.apps.silver.devops.gov.bc.ca/api/v1/graduatestudent?studentID={studentId}&gradProgram={gradProgram}
    grad-algorithm-api-projected: https://educ-grad-algorithm-api-77c02f-dev.apps.silver.devops.gov.bc.ca/api/v1/graduatestudent?studentID={studentId}&gradProgram={gradProgram}&projected={isProjected}
    #trax-api: https://educ-grad-trax-api-${gtts-properties.os-hosted-url}
    #batch-graduation-api: https://educ-grad-batch-graduation-api-${gtts-properties.os-hosted-url}
    #student-graduation-api: https://educ-grad-student-graduation-api-${gtts-properties.os-hosted-url}
    #graduation-api: https://educ-grad-graduation-api-${gtts-properties.os-hosted-url}
    #assessment-api: https://educ-grad-assessment-api-${gtts-properties.os-hosted-url}
    #graduation-report-api: https://educ-grad-graduation-report-api-${gtts-properties.os-hosted-url}
    #grad-report-api: https://educ-grad-report-api-${gtts-properties.os-hosted-url}
    #program-api: https://educ-grad-program-api-${gtts-properties.os-hosted-url}
