spring:
  main:
    web-application-type: none
    banner-mode: off
logging:
  level:
    root: off
gtts-properties:
  grad-api-base-url: https://dev.grad.gov.bc.ca/
  os-hosted-url: ${OS_HOSTED_URL}
  auth:
    student-api-client-id: ${STUDENT_API_CLIENT_ID}
    student-api-client-secret: ${STUDENT_API_CLIENT_SECRET}
    student-api-username: ${STUDENT_API_USERNAME}
    student-api-password: ${STUDENT_API_PASSWORD}
  service-endpoints:
    keycloak-auth-host: ${KEYCLOAK_AUTH_HOST}
    students-api: https://educ-grad-student-api-${gtts-properties.os-hosted-url}
    students-api-search-by-pen: https://educ-grad-student-api-${gtts-properties.os-hosted-url}/api/v1/student/pen/{pen}
    #trax-api: https://educ-grad-trax-api-${gtts-properties.os-hosted-url}
    #batch-graduation-api: https://educ-grad-batch-graduation-api-${gtts-properties.os-hosted-url}
    #student-graduation-api: https://educ-grad-student-graduation-api-${gtts-properties.os-hosted-url}
    #graduation-api: https://educ-grad-graduation-api-${gtts-properties.os-hosted-url}
    #assessment-api: https://educ-grad-assessment-api-${gtts-properties.os-hosted-url}
    #graduation-report-api: https://educ-grad-graduation-report-api-${gtts-properties.os-hosted-url}
    #grad-report-api: https://educ-grad-report-api-${gtts-properties.os-hosted-url}
    #program-api: https://educ-grad-program-api-${gtts-properties.os-hosted-url}
