spring:
  datasource:
    hikari:
      pool-name: educ-grad-trax-api-cp
      maximum-pool-size: 10
      connection-timeout: 60000
      max-lifetime: 60000
    url: ${TRAX_DB_CONNECTION_STRING}
    username: ${TRAX_DB_USERNAME}
    password: ${TRAX_DB_PASSWORD}
    driver-class: oracle.jdbc.driver.OracleDriver
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: none
gtts-properties:
  grad-api-base-url: https://dev.grad.gov.bc.ca/
  os-hosted-url: ${OS_HOSTED_URL}
  educ-grad-student-api: https://educ-grad-student-api-${gtts-properties.os-hosted-url}
  educ-grad-algorithm-api: https://educ-grad-algorithm-api-${gtts-properties.os-hosted-url}
  #educ-grad-student-api: http://localhost:8082
  #educ-grad-algorithm-api: http://localhost:8084
  auth:
    student-api-client-id: ${STUDENT_API_CLIENT_ID}
    student-api-client-secret: ${STUDENT_API_CLIENT_SECRET}
    student-api-username: ${STUDENT_API_USERNAME}
    student-api-password: ${STUDENT_API_PASSWORD}
  service-endpoints:
    keycloak-auth-host: ${KEYCLOAK_AUTH_HOST}
    students-api: ${gtts-properties.educ-grad-student-api}
    students-api-projectedgrad-list: ${gtts-properties.educ-grad-student-api}/api/v1/student/projected
    students-api-grad-list: ${gtts-properties.educ-grad-student-api}/api/v1/student/recalculate
    students-api-search-by-pen: ${gtts-properties.educ-grad-student-api}/api/v1/student/pen/{pen}
    students-api-search-by-id: ${gtts-properties.educ-grad-student-api}/api/v1/student/stdid/{stdid}
    grad-algorithm-api-graduate: ${gtts-properties.educ-grad-algorithm-api}/api/v1/graduatestudent?studentID={studentId}&gradProgram={gradProgram}
    grad-algorithm-api-projected: ${gtts-properties.educ-grad-algorithm-api}/api/v1/graduatestudent?studentID={studentId}&gradProgram={gradProgram}&projected={isProjected}

    #grad-algorithm-api-graduate: http://localhost:8084/api/v1/graduatestudent?studentID={studentId}&gradProgram={gradProgram}
    #grad-algorithm-api-projected: http://localhost:8084/api/v1/graduatestudent?studentID={studentId}&gradProgram={gradProgram}&projected={isProjected}
    #trax-api: https://educ-grad-trax-api-${gtts-properties.os-hosted-url}
    #batch-graduation-api: https://educ-grad-batch-graduation-api-${gtts-properties.os-hosted-url}
    #student-graduation-api: https://educ-grad-student-graduation-api-${gtts-properties.os-hosted-url}
    #graduation-api: https://educ-grad-graduation-api-${gtts-properties.os-hosted-url}
    #assessment-api: https://educ-grad-assessment-api-${gtts-properties.os-hosted-url}
    #graduation-report-api: https://educ-grad-graduation-report-api-${gtts-properties.os-hosted-url}
    #grad-report-api: https://educ-grad-report-api-${gtts-properties.os-hosted-url}
    #program-api: https://educ-grad-program-api-${gtts-properties.os-hosted-url}
  requirement-mappings:
    - program-name: "1950"
      rule-map:
        '500': "B"
        '501': "H"
        '502': "C"
        '504': "n/a"
        '503': "D"
        '505': "D"
        '506': "c"
        '507': "T"
    - program-name: "2004-EN"
      rule-map:
        '700': "g"
        '701': "r"
        '702': "A"
        '703': "B"
        '704': "a"
        '705': "C"
        '706': "b"
        '707': "H"
        '708': "t"
        '709': "I"
        '710': "V"
        '711': "l"
        '712': "U"
        '713': "W"
        '714': "i"
    - program-name: "2004-EN/CP"
      rule-map:
        '600': "n/a"
    - program-name: "2004-EN/FI"
      rule-map:
        '900': "n/a"
        '901': "n/a"
        '902': "n/a"
        '903': "n/a"
        '904': "n/a"
    - program-name: "2004-PF"
      rule-map:
        '700': "g"
        '704': "a"
        '705': "C"
        '706': "b"
        '707': "H"
        '708': "t"
        '709': "I"
        '710': "V"
        '711': "l"
        '712': "U"
        '713': "W"
        '714': "i"
        '815': "r"
        '816': "A"
        '817': "B"
    - program-name: "2004-PF/CP"
      rule-map:
        '600': "n/a"
    - program-name: "2004-PF/DD"
      rule-map:
        '850': "n/a"
        '851': "n/a"
        '852': "n/a"
    - program-name: "2018-EN"
      rule-map:
        '100': "g"
        '101': "r"
        '102': "A"
        '103': "B"
        '104': "a"
        '105': "h"
        '106': "b"
        '107': "H"
        '108': "t"
        '109': "I"
        '110': "j"
        '111': "k"
        '112': "m"
        '113': "n"
        '115': "p"
        '116': "o"
        '117': "i"
        '118': "q"
    - program-name: "2018-PF/CP"
      rule-map:
        '600': "n/a"
    - program-name: "2018-PF/DD"
      rule-map:
        '400': "n/a"
        '401': "n/a"
        '402': "n/a"
        '403': "n/a"
        '404': "n/a"
    - program-name: "NOPROG"
      rule-map:
        '675': "n/a"
    - program-name: "SCCP"
      rule-map:
        '650': "n/a"
    - program-name: "1996-EN"
      rule-map:
        '720': "R"
        '721': "A"
        '722': "B"
        '723': "C"
        '724': "H"
        '725': "I"
        '726': "N"
        '727': "O"
        '728': "P"
        '729': "Q"
        '730': "S"
        '731': "n/a"
        '732': "n/a"
    - program-name: "1996-EN/CP"
      rule-map:
        '600': "n/a"
    - program-name: "1996-EN/FI"
      rule-map:
        '910': "n/a"
        '911': "n/a"
        '912': "n/a"
    - program-name: "1996-PF"
      rule-map:
        '720': "R"
        '818': "A"
        '819': "B"
        '723': "C"
        '724': "H"
        '725': "I"
        '726': "N"
        '727': "O"
        '728': "P"
        '729': "Q"
        '730': "S"
        '820': "n/a"
        '731': "n/a"
    - program-name: "1986-EN"
      rule-map:
        '740': "A"
        '741': "B"
        '742': "C"
        '743': "H"
        '744': "I"
        '745': "J"
        '746': "F"
        '747': "D"
        '748': "n/a"
    - program-name: "1986-EN/FI"
      rule-map:
        '915': "n/a"
        '916': "n/a"
        '917': "n/a"


