name: DeployTests

env:
  OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
  OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
  OPENSHIFT_NAMESPACE: ${{ secrets.OPENSHIFT_NAMESPACE }}

  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  IMAGE_REGISTRY_USER: ${{ github.actor }}
  IMAGE_REGISTRY_PASSWORD: ${{ github.token }}

  IMAGE_TAGS: ""
  IMAGE_NAME: grad-test-automation

  DOCKER_ARTIFACTORY_REPO: docker-remote.artifacts.developer.gov.bc.ca
  ARTIFACTORY_REPO: artifacts.developer.gov.bc.ca

  APP_NAME: 'grad-test-automation'
  REPO_NAME: $APP_NAME
  JOB_NAME: "master"
  APP_NAME_FULL: $APP_NAME"-master"
  TAG: "latest"
  MIN_REPLICAS: "1"
  MAX_REPLICAS: "1"
  MIN_CPU: "50m"
  MAX_CPU: "500m"
  MIN_MEM: "500Mi"
  MAX_MEM: "2048Mi"

on:
  workflow_dispatch:

jobs:
  openshift-ci-cd:
    name: Build and deploy to OpenShift
    runs-on: ubuntu-18.04
    environment: test

    #outputs:
      #ROUTE: ${{ steps.deploy-and-expose.outputs.route }}
      #SELECTOR: ${{ steps.deploy-and-expose.outputs.selector }}

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Determine image tags
      if: env.IMAGE_TAGS == ''
      run: |
        echo "IMAGE_TAGS=latest ${GITHUB_SHA::12}" | tee -a $GITHUB_ENV

    - name: Install oc
      uses: redhat-actions/openshift-tools-installer@v1
      with:
        oc: 4.9.8

      # https://github.com/redhat-actions/oc-login#readme
    - uses: actions/checkout@v2
    - name: Deploy
      run: |
        set -eux
        # Login to OpenShift and select project
        oc login --token=${{ env.OPENSHIFT_TOKEN }} --server=${{ env.OPENSHIFT_SERVER }}
        oc project ${{ env.OPENSHIFT_NAMESPACE }}
        # Cancel any rollouts in progress
        oc rollout cancel dc/${{ env.IMAGE_NAME }} 2> /dev/null \
        || true && echo "No rollout in progress"
        oc tag ${{env.IMAGE_REGISTRY}}${{env.APP_FULL_NAME}}:${{env.TAG}} ${{ env.REPO_NAME }}-${{ env.JOB_NAME }}:${{ env.TAG }}
        # Process and apply deployment template
        oc process -f tools/openshift/tests.dc.yaml -p APP_NAME=${{ env.APP_NAME }} -p REPO_NAME=${{ env.REPO_NAME }} -p JOB_NAME=${{ env.JOB_NAME }} -p NAMESPACE=${{ env.OPENSHIFT_NAMESPACE }} -p TAG=${{ env.TAG }} -p MIN_REPLICAS=${{ env.MIN_REPLICAS }} -p MAX_REPLICAS=${{ env.MAX_REPLICAS }} -p MIN_CPU=${{ env.MIN_CPU }} -p MAX_CPU=${{ env.MAX_CPU }} -p MIN_MEM=${{ env.MIN_MEM }} -p MAX_MEM=${{ env.MAX_MEM }} | oc create -f -
        # Start rollout (if necessary) and follow it
        oc rollout latest dc/${{ env.IMAGE_NAME }}-${{ env.JOB_NAME }} 2> /dev/null \
        || true && echo "Rollout in progress"
        oc logs -f dc/${{ env.IMAGE_NAME }}-${{ env.JOB_NAME }}
        # Get status, returns 0 if rollout is successful
        oc rollout status dc/${{ env.IMAGE_NAME }}-${{ env.JOB_NAME }}
