# This is a basic workflow to help you get started with Actions

name: test

env:
  TARGET_ENV: "dev"
  HOST_ROUTE: "https://edx-d4cdde-${{ env.TARGET_ENV }}.apps.silver.devops.gov.bc.ca"

# Controls when the workflow will run
on: 
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: testEnv
    steps:
    - run: |
        echo "HOST_ROUTE="${{ env.HOST_ROUTE }}
