name: Smoke Test
env:
  DEFAULT_BASE_URL: https://dev.grad.gov.bc.ca/?login=noidir
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      BASE_URL:
        type: string
        description: The base url to test against, like http://grad.gov.bc.ca. Defaults to dev,
        required: false
        default: $DEFAULT_BASE_URL
    secrets:
      TEST_ADMIN_USERNAME:
        required: true
      TEST_ADMIN_PASSWORD:
        required: true
      TEST_PEN:
        required: true
jobs:
  SmokeTest:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v3
        with:
          # explicit repo pull. may be another caller.
          repository: bcgov/EDUC-GRAD-TEST-AUTOMATION
          ref: main
      - name: Sanity Check
        run: |
          echo "TEST_ADMIN_USERNAME: ${{ secrets.TEST_ADMIN_USERNAME }}"
          echo "TEST_ADMIN_PASSWORD: ${{ secrets.TEST_ADMIN_PASSWORD }}"
          echo "BASE_URL: ${{ secrets.BASE_URL }}"
          echo "TEST_PEN: ${{ secrets.TEST_PEN }}"
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm install
      - run: npm run smoke-test
        if: ${{ always() }}
        env:
          TEST_ADMIN_USERNAME: ${{ secrets.TEST_ADMIN_USERNAME }}
          TEST_ADMIN_PASSWORD: ${{ secrets.TEST_ADMIN_PASSWORD }}
          BASE_URL: ${{ inputs.BASE_URL == '' && $DEFAULT_BASE_URL || inputs.BASE_URL }}
          TEST_PEN: ${{ secrets.TEST_PEN }}
          API_HTML_STATUS_CLASS_THRESHOLD: 399
