name: Smoke Test
on:
  workflow_dispatch:
  workflow_call:
    secrets:
      TEST_ADMIN_USERNAME:
        required: true
      TEST_ADMIN_PASSWORD:
        required: true
      BASE_URL:
        required: true
      TEST_PEN:
        required: true
jobs:
  SmokeTest:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v3
        with:
          # explicit repo pull. may be another caller.
          repository: bcgov/EDUC-GRAD-TEST-AUTOMATION
          ref: main
      - name: Sanity Check
        run: |
          echo "TEST_ADMIN_USERNAME: ${{ secrets.TEST_ADMIN_USERNAME }}"
          echo "TEST_ADMIN_PASSWORD: ${{ secrets.TEST_ADMIN_PASSWORD }}"
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm install
      - run: npm run smoke-test
        if: ${{ always() }}
        env:
          TEST_ADMIN_USERNAME: ${{ secrets.TEST_ADMIN_USERNAME }}
          TEST_ADMIN_PASSWORD: ${{ secrets.TEST_ADMIN_PASSWORD }}
          BASE_URL: ${{ secrets.DEV_BASE_URL }}
          TEST_PEN: ${{ secrets.TEST_PEN }}
          API_HTML_STATUS_CLASS_THRESHOLD: 399
