# This is a basic workflow that is manually triggered

name: Testcafe Test

on:
  workflow_dispatch:

jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "10.x"
      - uses: Meemaw/testcafe-action@master
        with:
          args: "chrome:headless ./auto_test/test_cases"
